<?php

namespace AppBundle\Repository;

/**
 * ContactMeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactMeRepository extends \Doctrine\ORM\EntityRepository
{
}
